In [3]:
import pandas as pd
carros = ['jetta variant', 'Passat', 'Crossfox']

#as series, arrays unidimensionais rotulados capazes de armazenar qualquer tipo de dado.
#Os rótulos das linhas de uma series são conhecidos como index,

pd.Series(carros)

dados = [
    {'Nome': 'Jetta Variant', 'Motor': 'Motor 4.0 Turbo', 'Ano': 2003, 'Quilometragem': 44410.0, 'Zero_km': False, 'Valor': 88078.64},
    {'Nome': 'Passat', 'Motor': 'Motor Diesel', 'Ano': 1991, 'Quilometragem': 5712.0, 'Zero_km': False, 'Valor': 106161.94},
    {'Nome': 'Crossfox', 'Motor': 'Motor Diesel V8', 'Ano': 1990, 'Quilometragem': 37123.0, 'Zero_km': False, 'Valor': 72832.16}
]

dataset3 = pd.DataFrame(dados)

pd.set_option('display.max_rows',10)
pd.set_option('display.max_columns',100)

dataset = pd.read_csv ('dados/db.csv',sep =';',index_col=0)

dataset = pd.DataFrame(dataset)
#dataset.dtypes
#dataset.info()
#dataset[['Quilometragem','Valor']].describe()



dataset.head(2)

dataset[['Valor']]

                           Valor
Nome
Jetta Variant           88078.64
Passat                 106161.94
Crossfox                72832.16
DS5                    124549.07
Aston Martin DB4        92612.10
...                          ...
Phantom 2013            51759.58
Cadillac Ciel concept   51667.06
Classe GLK              68934.03
Aston Martin DB5       122110.90
Macan                   90381.47

[258 rows x 1 columns]

In [13]:
#vai bucar pelo rotulo (nome das colunas )
dataset.loc[['Passat','DS5']]#selecionado pelo index

,Motor,Ano,Quilometragem,Zero_km,Acessórios,Valor
Nome,,,,,,
Passat,Motor Diesel,1991,5712.0,False,"['Central multimídia', 'Teto panorâmico', 'Fre...",106161.94
DS5,Motor 2.4 Turbo,2019,NaN,True,"['Travas elétricas', '4 X 4', 'Vidros elétrico...",124549.07

In [14]:
dataset.loc[['Passat','DS5'],['Motor','Valor']] # seleciondo pelo index e pegando duas colunas

                  Motor      Valor
Nome
Passat     Motor Diesel  106161.94
DS5     Motor 2.4 Turbo  124549.07

In [15]:
#faz a busca pelo index numerico
dataset.iloc[1]

Motor                                                 Motor Diesel
Ano                                                           1991
Quilometragem                                               5712.0
Zero_km                                                      False
Acessórios       ['Central multimídia', 'Teto panorâmico', 'Fre...
Valor                                                    106161.94
Name: Passat, dtype: object

In [17]:
dataset.iloc[[1]]

,Motor,Ano,Quilometragem,Zero_km,Acessórios,Valor
Nome,,,,,,
Passat,Motor Diesel,1991,5712.0,False,"['Central multimídia', 'Teto panorâmico', 'Fre...",106161.94

In [18]:
dataset.iloc[1:4]

,Motor,Ano,Quilometragem,Zero_km,Acessórios,Valor
Nome,,,,,,
Passat,Motor Diesel,1991,5712.0,False,"['Central multimídia', 'Teto panorâmico', 'Fre...",106161.94
Crossfox,Motor Diesel V8,1990,37123.0,False,"['Piloto automático', 'Controle de estabilidad...",72832.16
DS5,Motor 2.4 Turbo,2019,NaN,True,"['Travas elétricas', '4 X 4', 'Vidros elétrico...",124549.07

In [23]:
dataset.iloc[1:4,[0,5,2]] #1:4, buscando por linda |[0,5,2] buscando por coluna

                    Motor      Valor  Quilometragem
Nome
Passat       Motor Diesel  106161.94         5712.0
Crossfox  Motor Diesel V8   72832.16        37123.0
DS5       Motor 2.4 Turbo  124549.07            NaN

In [ ]:
dataset.iloc[:,[0,5,2]]

In [24]:
import pandas as pd

dados = {
    'Nome': ['Jetta', 'Passat', 'Crossfox', 'DS5', 'Fusca'], 
    'Motor': ['Motor 4.0 Turbo', 'Motor Diesel', 'Motor Diesel V8', 'Motor 2.0', 'Motor 1.6'],
    'Ano': [2019, 2003, 1991, 2019, 1990],
    'Quilometragem': [0.0, 5712.0, 37123.0, 0.0, 120000.0],
    'Zero_km': [True, False, False, True, False],
    'Valor': [88000.0, 106000.0, 72000.0, 89000.0, 32000.0]
}

dataset = pd.DataFrame(dados)

In [37]:
dataset [1:3][['Nome','Ano','Quilometragem','Valor']]

       Nome   Ano  Quilometragem     Valor
1    Passat  2003         5712.0  106000.0
2  Crossfox  1991        37123.0   72000.0

In [39]:
import pandas as pd

dados = {
    'Motor': ['Motor 4.0 Turbo', 'Motor Diesel', 'Motor Diesel V8', 'Motor 2.0', 'Motor 1.6'],
    'Ano': [2019, 2003, 1991, 2019, 1990],
    'Quilometragem': [0.0, 5712.0, 37123.0, 0.0, 120000.0],
    'Zero_km': [True, False, False, True, False],
    'Valor': [88000.0, 106000.0, 72000.0, 89000.0, 32000.0]
}

dataset = pd.DataFrame(dados, index = ['Jetta', 'Passat', 'Crossfox', 'DS5', 'Fusca'])

In [40]:
dataset

                    Motor   Ano  Quilometragem  Zero_km     Valor
Jetta     Motor 4.0 Turbo  2019            0.0     True   88000.0
Passat       Motor Diesel  2003         5712.0    False  106000.0
Crossfox  Motor Diesel V8  1991        37123.0    False   72000.0
DS5             Motor 2.0  2019            0.0     True   89000.0
Fusca           Motor 1.6  1990       120000.0    False   32000.0

In [42]:
#Utilizando .loc, podemos fazer seleções 
#utilizando os rótulos das linhas e 
#colunas de um DataFrame.

dataset.loc[['Passat','DS5'],['Motor','Valor']]

               Motor     Valor
Passat  Motor Diesel  106000.0
DS5        Motor 2.0   89000.0

In [43]:
#Utilizando .iloc, as seleções são feitas pela 
#posição das linhas e colunas, isto é, utilizando
#os índices numéricos do DataFrame.

dataset.iloc[1:3,[0,4]]

                    Motor     Valor
Passat       Motor Diesel  106000.0
Crossfox  Motor Diesel V8   72000.0

In [2]:
dataset = pd.read_csv ('dados/db.csv',sep =';',index_col=0)

NameError: name 'pd' is not defined

In [45]:
dataset.head()

,Motor,Ano,Quilometragem,Zero_km,Acessórios,Valor
Nome,,,,,,
Jetta Variant,Motor 4.0 Turbo,2003,44410.0,False,"['Rodas de liga', 'Travas elétricas', 'Piloto ...",88078.64
Passat,Motor Diesel,1991,5712.0,False,"['Central multimídia', 'Teto panorâmico', 'Fre...",106161.94
Crossfox,Motor Diesel V8,1990,37123.0,False,"['Piloto automático', 'Controle de estabilidad...",72832.16
DS5,Motor 2.4 Turbo,2019,NaN,True,"['Travas elétricas', '4 X 4', 'Vidros elétrico...",124549.07
Aston Martin DB4,Motor 2.4 Turbo,2006,25757.0,False,"['Rodas de liga', '4 X 4', 'Central multimídia...",92612.10

In [48]:
select = dataset.Motor == 'Motor Diesel'
dataset[select]

,Motor,Ano,Quilometragem,Zero_km,Acessórios,Valor
Nome,,,,,,
Passat,Motor Diesel,1991,5712.0,False,"['Central multimídia', 'Teto panorâmico', 'Fre...",106161.94
Effa Hafei Picape Baú,Motor Diesel,1991,102959.0,False,"['Controle de estabilidade', 'Painel digital',...",125684.65
Sorento,Motor Diesel,2019,NaN,True,"['Sensor de chuva', 'Câmera de estacionamento'...",81399.35
New Fiesta Hatch,Motor Diesel,2017,118895.0,False,"['Sensor de estacionamento', 'Travas elétricas...",66007.16
Kangoo Express,Motor Diesel,2007,29132.0,False,"['Bancos de couro', 'Câmbio automático', 'Pilo...",146716.91
...,...,...,...,...,...,...
Dodge Dakota,Motor Diesel,1993,71544.0,False,"['Controle de tração', 'Sensor de estacionamen...",141083.35
i30 CW,Motor Diesel,2015,8497.0,False,"['Sensor de chuva', 'Vidros elétricos', 'Contr...",73311.75
Série 7 Sedã,Motor Diesel,2019,NaN,True,"['Vidros elétricos', 'Travas elétricas', 'Roda...",67539.79
V60,Motor Diesel,2004,91840.0,False,"['Rodas de liga', 'Sensor crepuscular', 'Ar co...",114728.74
Aston Martin DB5,Motor Diesel,1996,7685.0,False,"['Ar condicionado', '4 X 4', 'Câmbio automátic...",122110.90

In [53]:
dataset[(dataset.Motor == 'Motor Diesel') & (dataset.Zero_km == True)] # primeiro tipo de filtros

,Motor,Ano,Quilometragem,Zero_km,Acessórios,Valor
Nome,,,,,,
Sorento,Motor Diesel,2019,NaN,True,"['Sensor de chuva', 'Câmera de estacionamento'...",81399.35
Cielo Hatch,Motor Diesel,2019,NaN,True,"['Painel digital', 'Central multimídia', 'Câme...",145197.70
Camry,Motor Diesel,2019,NaN,True,"['Travas elétricas', 'Rodas de liga', 'Sensor ...",138597.27
Aston Martin Virage,Motor Diesel,2019,NaN,True,"['Travas elétricas', 'Controle de tração', 'Câ...",97290.18
Série 7 Sedã,Motor Diesel,2019,NaN,True,"['Vidros elétricos', 'Travas elétricas', 'Roda...",67539.79

In [55]:
dataset.query('Motor == "Motor Diesel" and Zero_km == True')# filtro com querys

,Motor,Ano,Quilometragem,Zero_km,Acessórios,Valor
Nome,,,,,,
Sorento,Motor Diesel,2019,NaN,True,"['Sensor de chuva', 'Câmera de estacionamento'...",81399.35
Cielo Hatch,Motor Diesel,2019,NaN,True,"['Painel digital', 'Central multimídia', 'Câme...",145197.70
Camry,Motor Diesel,2019,NaN,True,"['Travas elétricas', 'Rodas de liga', 'Sensor ...",138597.27
Aston Martin Virage,Motor Diesel,2019,NaN,True,"['Travas elétricas', 'Controle de tração', 'Câ...",97290.18
Série 7 Sedã,Motor Diesel,2019,NaN,True,"['Vidros elétricos', 'Travas elétricas', 'Roda...",67539.79

In [58]:
import pandas as pd

dados = {
    'Motor': ['Motor 4.0 Turbo', 'Motor Diesel', 'Motor Diesel V8', 'Motor Diesel', 'Motor 1.6'],
    'Ano': [2019, 2003, 1991, 2019, 1990],
    'Quilometragem': [0.0, 5712.0, 37123.0, 0.0, 120000.0],
    'Zero_km': [True, False, False, True, False],
    'Valor': [88000.0, 106000.0, 72000.0, 89000.0, 32000.0]
}

dataset = pd.DataFrame(dados, index = ['Jetta', 'Passat', 'Crossfox', 'DS5', 'Fusca'])
dataset

                    Motor   Ano  Quilometragem  Zero_km     Valor
Jetta     Motor 4.0 Turbo  2019            0.0     True   88000.0
Passat       Motor Diesel  2003         5712.0    False  106000.0
Crossfox  Motor Diesel V8  1991        37123.0    False   72000.0
DS5          Motor Diesel  2019            0.0     True   89000.0
Fusca           Motor 1.6  1990       120000.0    False   32000.0

In [60]:
dataset.query('Motor == "Motor Diesel" or Ano == 2019')

                  Motor   Ano  Quilometragem  Zero_km     Valor
Jetta   Motor 4.0 Turbo  2019            0.0     True   88000.0
Passat     Motor Diesel  2003         5712.0    False  106000.0
DS5        Motor Diesel  2019            0.0     True   89000.0

In [61]:
dataset.query('Motor == "Motor Diesel" or Zero_km == True')

                  Motor   Ano  Quilometragem  Zero_km     Valor
Jetta   Motor 4.0 Turbo  2019            0.0     True   88000.0
Passat     Motor Diesel  2003         5712.0    False  106000.0
DS5        Motor Diesel  2019            0.0     True   89000.0

In [4]:
dataset[(dataset.Motor=="Motor Diesel") | (dataset.Zero_km ==True)]

,Motor,Ano,Quilometragem,Zero_km,Acessórios,Valor
Nome,,,,,,
Passat,Motor Diesel,1991,5712.0,False,"['Central multimídia', 'Teto panorâmico', 'Fre...",106161.94
DS5,Motor 2.4 Turbo,2019,NaN,True,"['Travas elétricas', '4 X 4', 'Vidros elétrico...",124549.07
A5,Motor 4.0 Turbo,2019,NaN,True,"['Câmbio automático', 'Câmera de estacionament...",56445.20
J5,Motor V6,2019,NaN,True,"['Sensor crepuscular', 'Painel digital', 'Roda...",53183.38
A3,Motor 1.0 8v,2019,NaN,True,"['4 X 4', 'Piloto automático', 'Central multim...",88552.39
...,...,...,...,...,...,...
Benni Mini,Motor V8,2019,NaN,True,"['Sensor crepuscular', 'Câmbio automático', 'C...",126247.84
Uno,Motor Diesel V6,2019,NaN,True,"['Central multimídia', 'Sensor crepuscular', '...",128852.21
Santa Fe,Motor 3.0 32v,2019,NaN,True,"['Travas elétricas', 'Ar condicionado', '4 X 4...",129415.33
XC60,Motor 4.0 Turbo,2019,NaN,True,"['Painel digital', 'Piloto automático', 'Centr...",77675.79
Aston Martin DB5,Motor Diesel,1996,7685.0,False,"['Ar condicionado', '4 X 4', 'Câmbio automátic...",122110.90

In [10]:
for index, row in dataset.iterrows(): # pelo o index e as colunas  
    if(2019 - row['Ano'] !=0): 
        dataset.loc[index,'km_media'] = row['Quilometragem'] / (2019 - row['Ano']) #crio uma nova coluna 
    else:
        dataset.loc[index,'km_media'] = 0
dataset

,Motor,Ano,Quilometragem,Zero_km,Acessórios,Valor,km_media
Nome,,,,,,,
Jetta Variant,Motor 4.0 Turbo,2003,44410.0,False,"['Rodas de liga', 'Travas elétricas', 'Piloto ...",88078.64,2775.625000
Passat,Motor Diesel,1991,5712.0,False,"['Central multimídia', 'Teto panorâmico', 'Fre...",106161.94,204.000000
Crossfox,Motor Diesel V8,1990,37123.0,False,"['Piloto automático', 'Controle de estabilidad...",72832.16,1280.103448
DS5,Motor 2.4 Turbo,2019,NaN,True,"['Travas elétricas', '4 X 4', 'Vidros elétrico...",124549.07,0.000000
Aston Martin DB4,Motor 2.4 Turbo,2006,25757.0,False,"['Rodas de liga', '4 X 4', 'Central multimídia...",92612.10,1981.307692
...,...,...,...,...,...,...,...
Phantom 2013,Motor V8,2014,27505.0,False,"['Controle de estabilidade', 'Piloto automátic...",51759.58,5501.000000
Cadillac Ciel concept,Motor V8,1991,29981.0,False,"['Bancos de couro', 'Painel digital', 'Sensor ...",51667.06,1070.750000
Classe GLK,Motor 5.0 V8 Bi-Turbo,2002,52637.0,False,"['Rodas de liga', 'Controle de tração', 'Câmbi...",68934.03,3096.294118
Aston Martin DB5,Motor Diesel,1996,7685.0,False,"['Ar condicionado', '4 X 4', 'Câmbio automátic...",122110.90,334.130435
Macan,Motor Diesel V6,1992,50188.0,False,"['Central multimídia', 'Teto panorâmico', 'Vid...",90381.47,1858.814815

In [12]:
list(dataset.items())

[('Motor',
  Nome
  Jetta Variant                  Motor 4.0 Turbo
  Passat                            Motor Diesel
  Crossfox                       Motor Diesel V8
  DS5                            Motor 2.4 Turbo
  Aston Martin DB4               Motor 2.4 Turbo
                                   ...
  Phantom 2013                          Motor V8
  Cadillac Ciel concept                 Motor V8
  Classe GLK               Motor 5.0 V8 Bi-Turbo
  Aston Martin DB5                  Motor Diesel
  Macan                          Motor Diesel V6
  Name: Motor, Length: 258, dtype: object),
 ('Ano',
  Nome
  Jetta Variant            2003
  Passat                   1991
  Crossfox                 1990
  DS5                      2019
  Aston Martin DB4         2006
                           ...
  Phantom 2013             2014
  Cadillac Ciel concept    1991
  Classe GLK               2002
  Aston Martin DB5         1996
  Macan                    1992
  Name: Ano, Length: 258, dtype: int64),
 ('Quilometragem',
  Nome
  Jetta Variant            44410.0
  Passat                    5712.0
  Crossfox                 37123.0
  DS5                          NaN
  Aston Martin DB4         25757.0
                            ...
  Phantom 2013             27505.0
  Cadillac Ciel concept    29981.0
  Classe GLK               52637.0
  Aston Martin DB5          7685.0
  Macan                    50188.0
  Name: Quilometragem, Length: 258, dtype: float64),
 ('Zero_km',
  Nome
  Jetta Variant            False
  Passat                   False
  Crossfox                 False
  DS5                       True
  Aston Martin DB4         False
                           ...
  Phantom 2013             False
  Cadillac Ciel concept    False
  Classe GLK               False
  Aston Martin DB5         False
  Macan                    False
  Name: Zero_km, Length: 258, dtype: bool),
 ('Acessórios',
  Nome
  Jetta Variant            ['Rodas de liga', 'Travas elétricas', 'Piloto ...
  Passat                   ['Central multimídia', 'Teto panorâmico', 'Fre...
  Crossfox                 ['Piloto automático', 'Controle de estabilidad...
  DS5                      ['Travas elétricas', '4 X 4', 'Vidros elétrico...
  Aston Martin DB4         ['Rodas de liga', '4 X 4', 'Central multimídia...
                                                 ...
  Phantom 2013             ['Controle de estabilidade', 'Piloto automátic...
  Cadillac Ciel concept    ['Bancos de couro', 'Painel digital', 'Sensor ...
  Classe GLK               ['Rodas de liga', 'Controle de tração', 'Câmbi...
  Aston Martin DB5         ['Ar condicionado', '4 X 4', 'Câmbio automátic...
  Macan                    ['Central multimídia', 'Teto panorâmico', 'Vid...
  Name: Acessórios, Length: 258, dtype: object),
 ('Valor',
  Nome
  Jetta Variant             88078.64
  Passat                   106161.94
  Crossfox                  72832.16
  DS5                      124549.07
  Aston Martin DB4          92612.10
                             ...
  Phantom 2013              51759.58
  Cadillac Ciel concept     51667.06
  Classe GLK                68934.03
  Aston Martin DB5         122110.90
  Macan                     90381.47
  Name: Valor, Length: 258, dtype: float64),
 ('km_media',
  Nome
  Jetta Variant            2775.625000
  Passat                    204.000000
  Crossfox                 1280.103448
  DS5                         0.000000
  Aston Martin DB4         1981.307692
                              ...
  Phantom 2013             5501.000000
  Cadillac Ciel concept    1070.750000
  Classe GLK               3096.294118
  Aston Martin DB5          334.130435
  Macan                    1858.814815
  Name: km_media, Length: 258, dtype: float64)]

In [13]:
list(dataset.itertuples())

[Pandas(Index='Jetta Variant', Motor='Motor 4.0 Turbo', Ano=2003, Quilometragem=44410.0, Zero_km=False, Acessórios="['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva']", Valor=88078.64, km_media=2775.625),
 Pandas(Index='Passat', Motor='Motor Diesel', Ano=1991, Quilometragem=5712.0, Zero_km=False, Acessórios="['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento']", Valor=106161.94, km_media=204.0),
 Pandas(Index='Crossfox', Motor='Motor Diesel V8', Ano=1990, Quilometragem=37123.0, Zero_km=False, Acessórios="['Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']", Valor=72832.16, km_media=1280.103448275862),
 Pandas(Index='DS5', Motor='Motor 2.4 Turbo', Ano=2019, Quilometragem=nan, Zero_km=True, Acessórios="['Travas elétricas', '4 X 4', 'Vidros elétricos', 'Sensor crepuscular', 'Sensor de chuva', 'Câmera de estacionamento', 'Ar condicionado', 'Rodas de liga']", Valor=124549.07, km_media=0.0),
 Pandas(Index='Aston Martin DB4', Motor='Motor 2.4 Turbo', Ano=2006, Quilometragem=25757.0, Zero_km=False, Acessórios="['Rodas de liga', '4 X 4', 'Central multimídia', 'Ar condicionado', 'Controle de estabilidade', 'Câmbio automático', 'Sensor de estacionamento', 'Piloto automático']", Valor=92612.1, km_media=1981.3076923076924),
 Pandas(Index='Palio Weekend', Motor='Motor 1.8 16v', Ano=2012, Quilometragem=10728.0, Zero_km=False, Acessórios="['Sensor de estacionamento', 'Teto panorâmico', 'Sensor crepuscular', 'Painel digital', 'Ar condicionado', 'Rodas de liga', 'Controle de estabilidade', 'Bancos de couro']", Valor=97497.73, km_media=1532.5714285714287),
 Pandas(Index='A5', Motor='Motor 4.0 Turbo', Ano=2019, Quilometragem=nan, Zero_km=True, Acessórios="['Câmbio automático', 'Câmera de estacionamento', 'Freios ABS', 'Controle de tração', 'Central multimídia', 'Travas elétricas', 'Sensor crepuscular', 'Rodas de liga']", Valor=56445.2, km_media=0.0),
 Pandas(Index='Série 3 Cabrio', Motor='Motor 1.0 8v', Ano=2009, Quilometragem=77599.0, Zero_km=False, Acessórios="['Controle de estabilidade', 'Sensor crepuscular', 'Controle de tração', 'Teto panorâmico', 'Travas elétricas', 'Piloto automático', 'Painel digital', 'Câmera de estacionamento']", Valor=112310.44, km_media=7759.9),
 Pandas(Index='Dodge Jorney', Motor='Motor 3.0 32v', Ano=2010, Quilometragem=99197.0, Zero_km=False, Acessórios="['Vidros elétricos', 'Piloto automático', 'Teto panorâmico', 'Ar condicionado', 'Bancos de couro', 'Câmbio automático', 'Rodas de liga', 'Travas elétricas']", Valor=120716.27, km_media=11021.888888888889),
 Pandas(Index='Carens', Motor='Motor 5.0 V8 Bi-Turbo', Ano=2011, Quilometragem=37978.0, Zero_km=False, Acessórios="['Ar condicionado', 'Painel digital', 'Central multimídia', 'Sensor crepuscular', 'Câmbio automático', 'Rodas de liga', 'Controle de tração', 'Câmera de estacionamento']", Valor=76566.49, km_media=4747.25),
 Pandas(Index='Ford Edge', Motor='Motor Diesel V6', Ano=2002, Quilometragem=12859.0, Zero_km=False, Acessórios="['Sensor crepuscular', 'Rodas de liga', 'Teto panorâmico', 'Sensor de chuva', 'Travas elétricas', 'Sensor de estacionamento', 'Controle de tração', 'Ar condicionado']", Valor=71647.59, km_media=756.4117647058823),
 Pandas(Index='Courier', Motor='Motor Diesel V8', Ano=2007, Quilometragem=8052.0, Zero_km=False, Acessórios="['Central multimídia', '4 X 4', 'Piloto automático', 'Teto panorâmico', 'Controle de estabilidade', 'Câmera de estacionamento', 'Bancos de couro', 'Vidros elétricos']", Valor=73919.53, km_media=671.0),
 Pandas(Index='S-18', Motor='Motor V6', Ano=2001, Quilometragem=89773.0, Zero_km=False, Acessórios="['Bancos de couro', 'Sensor de chuva', 'Rodas de liga', 'Central multimídia', 'Travas elétricas', 'Ar condicionado', 'Câmera de estacionamento', 'Sensor crepuscular']", Valor=112732.99, km_media=4987.388888888889),
 Pandas(Index='J5', Motor='Motor V6', Ano=2019, Quilometragem=nan, Zero_km=True, Acessórios="['Sensor crepuscular', 'Painel digital', 'Rodas de liga', 'Freios ABS', 'Câmbio automático', 'Controle de tração', 'Central multimídia', 'Câmera de estacionamento']", Valor=53183.38, km_media=0.0),
 Pandas(Index='F-Type Coupé', Motor='Motor 5.0 V8 Bi-Turbo', Ano=2009, Quilometragem=41457.0, Zero_km=False, Acessórios="['Piloto automático', 'Sensor crepuscular', 'Sensor de chuva', 'Ar condicionado', 'Sensor de estacionamento', 'Controle de tração', 'Câmera de estacionamento', 'Vidros elétricos']", Valor=127488.42, km_media=4145.7),
 Pandas(Index='RAM', Motor='Motor Diesel V8', Ano=2016, Quilometragem=115607.0, Zero_km=False, Acessórios="['Sensor crepuscular', 'Câmbio automático', 'Sensor de chuva', 'Central multimídia', 'Controle de estabilidade', '4 X 4', 'Freios ABS', 'Piloto automático']", Valor=59910.4, km_media=38535.666666666664),
 Pandas(Index='Série 1', Motor='Motor 3.0 32v', Ano=2012, Quilometragem=46449.0, Zero_km=False, Acessórios="['Teto panorâmico', 'Câmera de estacionamento', 'Travas elétricas', '4 X 4', 'Painel digital', 'Central multimídia', 'Rodas de liga', 'Freios ABS']", Valor=61118.59, km_media=6635.571428571428),
 Pandas(Index='A3', Motor='Motor 1.0 8v', Ano=2019, Quilometragem=nan, Zero_km=True, Acessórios="['4 X 4', 'Piloto automático', 'Central multimídia', 'Teto panorâmico', 'Sensor de estacionamento', 'Controle de tração', 'Controle de estabilidade', 'Sensor de chuva']", Valor=88552.39, km_media=0.0),
 Pandas(Index='XC90', Motor='Motor 1.0 8v', Ano=2016, Quilometragem=37086.0, Zero_km=False, Acessórios="['Travas elétricas', 'Vidros elétricos', 'Teto panorâmico', 'Central multimídia', 'Controle de estabilidade', '4 X 4', 'Câmbio automático', 'Sensor de chuva']", Valor=62696.69, km_media=12362.0),
 Pandas(Index='RS 3 Sportback', Motor='Motor 3.0 32v', Ano=2017, Quilometragem=15173.0, Zero_km=False, Acessórios="['4 X 4', 'Piloto automático', 'Central multimídia', 'Bancos de couro', 'Sensor de chuva', 'Rodas de liga', 'Ar condicionado', 'Sensor crepuscular']", Valor=101726.3, km_media=7586.5),
 Pandas(Index='Pajero Sport', Motor='Motor 1.0 8v', Ano=2002, Quilometragem=101193.0, Zero_km=False, Acessórios="['Sensor de estacionamento', 'Piloto automático', 'Câmbio automático', 'Painel digital', 'Freios ABS', 'Câmera de estacionamento', 'Rodas de liga', 'Controle de estabilidade']", Valor=106147.38, km_media=5952.529411764706),
 Pandas(Index='Série 1 M', Motor='Motor V8', Ano=2019, Quilometragem=nan, Zero_km=True, Acessórios="['Controle de estabilidade', 'Central multimídia', 'Painel digital', 'Sensor crepuscular', 'Sensor de chuva', 'Câmera de estacionamento', 'Ar condicionado', 'Freios ABS']", Valor=94564.4, km_media=0.0),
 Pandas(Index='Lamborghini Obvious', Motor='Motor Diesel V6', Ano=1994, Quilometragem=98079.0, Zero_km=False, Acessórios="['Rodas de liga', 'Câmbio automático', 'Travas elétricas', 'Teto panorâmico', 'Controle de estabilidade', 'Central multimídia', 'Sensor de estacionamento', 'Sensor crepuscular']", Valor=133529.84, km_media=3923.16),
 Pandas(Index='Effa Hafei Picape Baú', Motor='Motor Diesel', Ano=1991, Quilometragem=102959.0, Zero_km=False, Acessórios="['Controle de estabilidade', 'Painel digital', 'Vidros elétricos', '4 X 4', 'Sensor crepuscular', 'Ar condicionado', 'Travas elétricas', 'Central multimídia']", Valor=125684.65, km_media=3677.1071428571427),
 Pandas(Index='Lamborghini Murciélago', Motor='Motor 5.0 V8 Bi-Turbo', Ano=2019, Quilometragem=nan, Zero_km=True, Acessórios="['Freios ABS', 'Câmbio automático', 'Ar condicionado', 'Câmera de estacionamento', 'Controle de tração', 'Central multimídia', 'Sensor crepuscular', 'Controle de estabilidade']", Valor=121596.21, km_media=0.0),
 Pandas(Index='Up!', Motor='Motor Diesel V6', Ano=2019, Quilometragem=nan, Zero_km=True, Acessórios="['Sensor de estacionamento', 'Vidros elétricos', 'Freios ABS', 'Central multimídia', 'Controle de estabilidade', 'Sensor de chuva', 'Câmbio automático', 'Piloto automático']", Valor=71367.1, km_media=0.0),
 Pandas(Index='Fiesta Rocam Sedan', Motor='Motor 4.0 Turbo', Ano=2016, Quilometragem=5795.0, Zero_km=False, Acessórios="['Ar condicionado', 'Bancos de couro', 'Câmbio automático', 'Câmera de estacionamento', 'Piloto automático', 'Controle de estabilidade', 'Sensor de chuva', 'Vidros elétricos']", Valor=95347.75, km_media=1931.6666666666667),
 Pandas(Index='Sandero Stepway', Motor='Motor 3.0 32v', Ano=2019, Quilometragem=nan, Zero_km=True, Acessórios="['Freios ABS', 'Ar condicionado', 'Teto panorâmico', 'Painel digital', 'Sensor de estacionamento', 'Vidros elétricos', 'Sensor crepuscular', 'Piloto automático']", Valor=105432.84, km_media=0.0),
 Pandas(Index='Cayman S', Motor='Motor 3.0 32v', Ano=2002, Quilometragem=58848.0, Zero_km=False, Acessórios="['Câmbio automático', 'Sensor de estacionamento', 'Rodas de liga', 'Vidros elétricos', '4 X 4', 'Bancos de couro', 'Painel digital', 'Travas elétricas']", Valor=57045.27, km_media=3461.6470588235293),
 Pandas(Index='V40', Motor='Motor 4.0 Turbo', Ano=1991, Quilometragem=94381.0, Zero_km=False, Acessórios="['Câmera de estacionamento', 'Sensor de estacionamento', 'Rodas de liga', 'Controle de tração', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Sensor de chuva']", Valor=120432.7, km_media=3370.75),
 Pandas(Index='Classe SLS AMG', Motor='Motor 1.0 8v', Ano=1997, Quilometragem=30163.0, Zero_km=False, Acessórios="['Sensor de estacionamento', 'Controle de estabilidade', 'Sensor de chuva', 'Travas elétricas', 'Painel digital', 'Sensor crepuscular', 'Piloto automático', 'Bancos de couro']", Valor=70707.2, km_media=1371.0454545454545),
 Pandas(Index='Gol G4', Motor='Motor 2.0 16v', Ano=1995, Quilometragem=53332.0, Zero_km=False, Acessórios="['Sensor crepuscular', '4 X 4', 'Vidros elétricos', 'Controle de tração', 'Ar condicionado', 'Câmera de estacionamento', 'Painel digital', 'Freios ABS']", Valor=69105.18, km_media=2222.1666666666665),
 Pandas(Index='Linea', Motor='Motor 1.0 8v', Ano=2018, Quilometragem=17720.0, Zero_km=False, Acessórios="['Piloto automático', 'Painel digital', 'Vidros elétricos', 'Controle de tração', 'Teto panorâmico', 'Ar condicionado', 'Câmera de estacionamento', 'Rodas de liga']", Valor=59358.69, km_media=17720.0),
 Pandas(Index='Ford F100', Motor='Motor 2.0 16v', Ano=1991, Quilometragem=33808.0, Zero_km=False, Acessórios="['Controle de tração', 'Sensor crepuscular', 'Travas elétricas', 'Bancos de couro', 'Câmera de estacionamento', 'Rodas de liga', 'Central multimídia', '4 X 4']", Valor=65955.4, km_media=1207.4285714285713),
 Pandas(Index='J2', Motor='Motor V8', Ano=2014, Quilometragem=90684.0, Zero_km=False, Acessórios="['Teto panorâmico', 'Sensor de estacionamento', 'Bancos de couro', 'Vidros elétricos', 'Freios ABS', 'Rodas de liga', 'Travas elétricas', 'Câmbio automático']", Valor=60017.03, km_media=18136.8),
 Pandas(Index='Aston Martin DBS', Motor='Motor V8', Ano=1995, Quilometragem=43975.0, Zero_km=False, Acessórios="['Teto panorâmico', 'Piloto automático', 'Ar condicionado', 'Vidros elétricos', 'Bancos de couro', 'Travas elétricas', 'Sensor de chuva', 'Sensor crepuscular']", Valor=118909.52, km_media=1832.2916666666667),
 Pandas(Index='Pajero TR4', Motor='Motor 2.4 Turbo', Ano=2019, Quilometragem=nan, Zero_km=True, Acessórios="['Controle de tração', 'Bancos de couro', 'Câmera de estacionamento', 'Controle de estabilidade', 'Vidros elétricos', 'Piloto automático', 'Rodas de liga', 'Teto panorâmico']", Valor=51606.59, km_media=0.0),
 Pandas(Index='Polo Sedan', Motor='Motor V6', Ano=2019, Quilometragem=nan, Zero_km=True, Acessórios="['Sensor de chuva', 'Sensor crepuscular', 'Ar condicionado', 'Sensor de estacionamento', 'Teto panorâmico', 'Câmbio automático', 'Vidros elétricos', 'Travas elétricas']", Valor=123281.87, km_media=0.0),
 Pandas(Index='California', Motor='Motor 1.0 8v', Ano=2009, Quilometragem=5526.0, Zero_km=False, Acessórios="['Rodas de liga', 'Ar condicionado', 'Câmera de estacionamento', 'Painel digital', 'Travas elétricas', 'Sensor crepuscular', 'Central multimídia', 'Freios ABS']", Valor=69770.18, km_media=552.6),
 Pandas(Index='S60', Motor='Motor 2.4 Turbo', Ano=2019, Quilometragem=nan, Zero_km=True, Acessórios="['Teto panorâmico', 'Freios ABS', '4 X 4', 'Ar condicionado', 'Controle de tração', 'Central multimídia', 'Painel digital', 'Sensor crepuscular']", Valor=102609.54, km_media=0.0),
 Pandas(Index='Tucson', Motor='Motor 2.0 16v', Ano=2013, Quilometragem=93415.0, Zero_km=False, Acessórios="['Vidros elétricos', 'Sensor crepuscular', 'Freios ABS', 'Câmera de estacionamento', 'Piloto automático', 'Travas elétricas', 'Câmbio automático', '4 X 4']", Valor=67997.19, km_media=15569.166666666666),
 Pandas(Index='HB20', Motor='Motor V6', Ano=2003, Quilometragem=40762.0, Zero_km=False, Acessórios="['Sensor de chuva', 'Travas elétricas', 'Controle de tração', 'Freios ABS', 'Ar condicionado', 'Teto panorâmico', 'Vidros elétricos', 'Câmbio automático']", Valor=135235.29, km_media=2547.625),
 Pandas(Index='Optima', Motor='Motor 1.8 16v', Ano=2019, Quilometragem=nan, Zero_km=True, Acessórios="['Central multimídia', 'Ar condicionado', 'Teto panorâmico', 'Freios ABS', 'Painel digital', 'Controle de estabilidade', '4 X 4', 'Sensor de estacionamento']", Valor=86641.34, km_media=0.0),
 Pandas(Index='Logan', Motor='Motor 4.0 Turbo', Ano=2002, Quilometragem=86302.0, Zero_km=False, Acessórios="['Câmera de estacionamento', 'Vidros elétricos', 'Central multimídia', 'Sensor de chuva', 'Sensor crepuscular', 'Painel digital', 'Ar condicionado', 'Bancos de couro']", Valor=136818.39, km_media=5076.588235294118),
 Pandas(Index='Range Rover Vogue', Motor='Motor 1.0 8v', Ano=2019, Quilometragem=nan, Zero_km=True, Acessórios="['4 X 4', 'Vidros elétricos', 'Rodas de liga', 'Central multimídia', 'Câmera de estacionamento', 'Sensor de estacionamento', 'Piloto automático', 'Ar condicionado']", Valor=117626.73, km_media=0.0),
 Pandas(Index='Sonata', Motor='Motor 5.0 V8 Bi-Turbo', Ano=2002, Quilometragem=9755.0, Zero_km=False, Acessórios="['Piloto automático', 'Ar condicionado', 'Vidros elétricos', '4 X 4', 'Sensor de estacionamento', 'Bancos de couro', 'Travas elétricas', 'Controle de estabilidade']", Valor=56208.7, km_media=573.8235294117648),
 Pandas(Index='Ford New Fiesta Sedan', Motor='Motor 3.0 32v', Ano=2004, Quilometragem=69945.0, Zero_km=False, Acessórios="['Teto panorâmico', 'Painel digital', 'Ar condicionado', 'Central multimídia', '4 X 4', 'Controle de estabilidade', 'Câmbio automático', 'Sensor de chuva']", Valor=84222.65, km_media=4663.0),
 Pandas(Index='Série 5 Gran Turismo', Motor='Motor 4.0 Turbo', Ano=2001, Quilometragem=2395.0, Zero_km=False, Acessórios="['Controle de tração', 'Piloto automático', 'Ar condicionado', 'Bancos de couro', 'Freios ABS', 'Central multimídia', 'Sensor de chuva', '4 X 4']", Valor=90781.65, km_media=133.05555555555554),
 Pandas(Index='CR-V', Motor='Motor Diesel V8', Ano=2019, Quilometragem=nan, Zero_km=True, Acessórios="['Câmbio automático', 'Central multimídia', 'Vidros elétricos', 'Controle de estabilidade', 'Controle de tração', 'Bancos de couro', 'Freios ABS', 'Painel digital']", Valor=64701.1, km_media=0.0),
 Pandas(Index='Ford EcoSport', Motor='Motor 1.0 8v', Ano=2003, Quilometragem=80349.0, Zero_km=False, Acessórios="['Vidros elétricos', 'Piloto automático', 'Painel digital', 'Freios ABS', 'Bancos de couro', 'Teto panorâmico', 'Sensor de chuva', 'Rodas de liga']", Valor=126350.49, km_media=5021.8125),
 Pandas(Index='Versa', Motor='Motor 3.0 32v', Ano=2009, Quilometragem=85554.0, Zero_km=False, Acessórios="['Bancos de couro', 'Ar condicionado', 'Rodas de liga', 'Sensor crepuscular', 'Travas elétricas', 'Sensor de estacionamento', 'Piloto automático', 'Controle de estabilidade']", Valor=148152.89, km_media=8555.4),
 Pandas(Index='Classe E', Motor='Motor 1.0 8v', Ano=2006, Quilometragem=50496.0, Zero_km=False, Acessórios="['Freios ABS', 'Sensor de estacionamento', 'Central multimídia', 'Câmera de estacionamento', 'Ar condicionado', 'Teto panorâmico', 'Câmbio automático', 'Piloto automático']", Valor=132298.83, km_media=3884.3076923076924),
 Pandas(Index='Carnival', Motor='Motor V8', Ano=2000, Quilometragem=67716.0, Zero_km=False, Acessórios="['Travas elétricas', 'Câmbio automático', 'Câmera de estacionamento', 'Freios ABS', 'Central multimídia', 'Rodas de liga', 'Teto panorâmico', 'Controle de estabilidade']", Valor=137627.63, km_media=3564.0),
 Pandas(Index='Aston Martin V8 Vantage Roadster', Motor='Motor 2.4 Turbo', Ano=2006, Quilometragem=93947.0, Zero_km=False, Acessórios="['Câmbio automático', 'Câmera de estacionamento', 'Vidros elétricos', 'Controle de estabilidade', 'Central multimídia', 'Piloto automático', 'Sensor crepuscular', 'Travas elétricas']", Valor=80422.71, km_media=7226.692307692308),
 Pandas(Index='Hoggar', Motor='Motor 5.0 V8 Bi-Turbo', Ano=2010, Quilometragem=35345.0, Zero_km=False, Acessórios="['Controle de estabilidade', 'Bancos de couro', 'Sensor de chuva', 'Painel digital', 'Vidros elétricos', 'Freios ABS', 'Controle de tração', 'Ar condicionado']", Valor=56373.99, km_media=3927.222222222222),
 Pandas(Index='A1', Motor='Motor 5.0 V8 Bi-Turbo', Ano=1994, Quilometragem=81007.0, Zero_km=False, Acessórios="['Painel digital', 'Câmbio automático', 'Câmera de estacionamento', 'Freios ABS', 'Controle de estabilidade', 'Sensor crepuscular', '4 X 4', 'Ar condicionado']", Valor=70846.03, km_media=3240.28),
 Pandas(Index='Aston Martin DB7 Vantage', Motor='Motor V6', Ano=2007, Quilometragem=119513.0, Zero_km=False, Acessórios="['Sensor crepuscular', 'Piloto automático', 'Teto panorâmico', 'Freios ABS', 'Câmbio automático', 'Central multimídia', 'Vidros elétricos', 'Sensor de estacionamento']", Valor=128694.23, km_media=9959.416666666666),
 Pandas(Index='CLA', Motor='Motor 1.0 8v', Ano=2019, Quilometragem=nan, Zero_km=True, Acessórios="['Central multimídia', 'Sensor de chuva', 'Controle de estabilidade', 'Sensor crepuscular', 'Rodas de liga', 'Piloto automático', '4 X 4', 'Vidros elétricos']", Valor=133329.19, km_media=0.0),
 Pandas(Index='Accord', Motor='Motor V8', Ano=2019, Quilometragem=nan, Zero_km=True, Acessórios="['Sensor de estacionamento', 'Ar condicionado', 'Central multimídia', 'Controle de tração', 'Rodas de liga', 'Teto panorâmico', 'Sensor de chuva', 'Câmera de estacionamento']", Valor=131961.43, km_media=0.0),
 Pandas(Index='EXTRA 103EX', Motor='Motor 2.0 16v', Ano=2019, Quilometragem=nan, Zero_km=True, Acessórios="['Sensor de estacionamento', 'Central multimídia', 'Bancos de couro', 'Sensor crepuscular', 'Teto panorâmico', 'Controle de tração', 'Piloto automático', 'Sensor de chuva']", Valor=112033.27, km_media=0.0),
 Pandas(Index='Sorento', Motor='Motor Diesel', Ano=2019, Quilometragem=nan, Zero_km=True, Acessórios="['Sensor de chuva', 'Câmera de estacionamento', 'Sensor de estacionamento', 'Controle de estabilidade', 'Rodas de liga', 'Travas elétricas', 'Vidros elétricos', 'Controle de tração']", Valor=81399.35, km_media=0.0),
 Pandas(Index='Tiggo', Motor='Motor 3.0 32v', Ano=2019, Quilometragem=nan, Zero_km=True, Acessórios="['Câmera de estacionamento', 'Freios ABS', 'Piloto automático', 'Vidros elétricos', 'Câmbio automático', 'Sensor crepuscular', 'Sensor de estacionamento', 'Controle de tração']", Valor=97163.1, km_media=0.0),
 Pandas(Index='New Fiesta Hatch', Motor='Motor Diesel', Ano=2017, Quilometragem=118895.0, Zero_km=False, Acessórios="['Sensor de estacionamento', 'Travas elétricas', 'Piloto automático', 'Rodas de liga', 'Controle de tração', 'Ar condicionado', '4 X 4', 'Sensor crepuscular']", Valor=66007.16, km_media=59447.5),

In [16]:
#tratamento de dados 
dataset

,Motor,Ano,Quilometragem,Zero_km,Acessórios,Valor,km_media
Nome,,,,,,,
Jetta Variant,Motor 4.0 Turbo,2003,44410.0,False,"['Rodas de liga', 'Travas elétricas', 'Piloto ...",88078.64,2775.625000
Passat,Motor Diesel,1991,5712.0,False,"['Central multimídia', 'Teto panorâmico', 'Fre...",106161.94,204.000000
Crossfox,Motor Diesel V8,1990,37123.0,False,"['Piloto automático', 'Controle de estabilidad...",72832.16,1280.103448
DS5,Motor 2.4 Turbo,2019,NaN,True,"['Travas elétricas', '4 X 4', 'Vidros elétrico...",124549.07,0.000000
Aston Martin DB4,Motor 2.4 Turbo,2006,25757.0,False,"['Rodas de liga', '4 X 4', 'Central multimídia...",92612.10,1981.307692
...,...,...,...,...,...,...,...
Phantom 2013,Motor V8,2014,27505.0,False,"['Controle de estabilidade', 'Piloto automátic...",51759.58,5501.000000
Cadillac Ciel concept,Motor V8,1991,29981.0,False,"['Bancos de couro', 'Painel digital', 'Sensor ...",51667.06,1070.750000
Classe GLK,Motor 5.0 V8 Bi-Turbo,2002,52637.0,False,"['Rodas de liga', 'Controle de tração', 'Câmbi...",68934.03,3096.294118
Aston Martin DB5,Motor Diesel,1996,7685.0,False,"['Ar condicionado', '4 X 4', 'Câmbio automátic...",122110.90,334.130435
Macan,Motor Diesel V6,1992,50188.0,False,"['Central multimídia', 'Teto panorâmico', 'Vid...",90381.47,1858.814815

In [17]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 258 entries, Jetta Variant to Macan
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Motor          258 non-null    object
 1   Ano            258 non-null    int64
 2   Quilometragem  197 non-null    float64
 3   Zero_km        258 non-null    bool
 4   Acessórios     258 non-null    object
 5   Valor          258 non-null    float64
 6   km_media       258 non-null    float64
dtypes: bool(1), float64(3), int64(1), object(2)
memory usage: 22.5+ KB

In [18]:
#retona um bolean aonde true é nan e false contem registro
dataset.Quilometragem.isna()

Nome
Jetta Variant            False
Passat                   False
Crossfox                 False
DS5                       True
Aston Martin DB4         False
                         ...
Phantom 2013             False
Cadillac Ciel concept    False
Classe GLK               False
Aston Martin DB5         False
Macan                    False
Name: Quilometragem, Length: 258, dtype: bool

In [19]:
#selecionando apenas os nan na quilometragem
dataset[dataset.Quilometragem.isna()]

,Motor,Ano,Quilometragem,Zero_km,Acessórios,Valor,km_media
Nome,,,,,,,
DS5,Motor 2.4 Turbo,2019,NaN,True,"['Travas elétricas', '4 X 4', 'Vidros elétrico...",124549.07,0.0
A5,Motor 4.0 Turbo,2019,NaN,True,"['Câmbio automático', 'Câmera de estacionament...",56445.20,0.0
J5,Motor V6,2019,NaN,True,"['Sensor crepuscular', 'Painel digital', 'Roda...",53183.38,0.0
A3,Motor 1.0 8v,2019,NaN,True,"['4 X 4', 'Piloto automático', 'Central multim...",88552.39,0.0
Série 1 M,Motor V8,2019,NaN,True,"['Controle de estabilidade', 'Central multimíd...",94564.40,0.0
...,...,...,...,...,...,...,...
Lamborghini Reventón,Motor 4.0 Turbo,2019,NaN,True,"['Controle de tração', 'Ar condicionado', 'Cen...",67664.86,0.0
Benni Mini,Motor V8,2019,NaN,True,"['Sensor crepuscular', 'Câmbio automático', 'C...",126247.84,0.0
Uno,Motor Diesel V6,2019,NaN,True,"['Central multimídia', 'Sensor crepuscular', '...",128852.21,0.0
Santa Fe,Motor 3.0 32v,2019,NaN,True,"['Travas elétricas', 'Ar condicionado', '4 X 4...",129415.33,0.0
XC60,Motor 4.0 Turbo,2019,NaN,True,"['Painel digital', 'Piloto automático', 'Centr...",77675.79,0.0

In [21]:
#inserir o registro dentro do dataframe 
dataset.fillna(0, inplace = True) # não tem retorno mas o inplece sobrescreve os nan

In [23]:
dataset = pd.read_csv ('dados/db.csv',sep =';',index_col=0)
#deletar os nan
dataset.dropna(subset = ['Quilometragem'],inplace = True)